version: 2

jobs:
  test-clj:
    docker:
      - image: circleci/clojure:lein-2.8.1

    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein deps
      - run: lein test
      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "project.clj" }}

  test-cljs:
    docker:
      - image: circleci/clojure:lein-2.8.1

    steps:
      - checkout
      - run: lein test-cljs

workflows:
  version: 2
  test:
    jobs:
      - test-clj
      - test-cljs
